import Head from 'next/head'
import MainLayout from '@/layouts/MainLayout'

export default function DataProtection() {

  return (
    <>
      <Head>
        <title>Datenschutzerklärung - AirClean VS</title>
      </Head>

      <MainLayout>
        <div className="py-[90px]">

          <div className="px-6 lg:px-8">
            <div className="relative mx-auto max-w-[37.5rem] text-center pt-14 lg:pt-20 pb-2 lg:pb-8">
              <h1 className="text-4xl font-extrabold tracking-tight text-slate-900 sm:text-5xl">Datenschutzerklärung</h1>
            </div>
          </div>

          <div className="relative px-6 lg:px-8">
            <div className="mx-auto max-w-[40rem] text-sm text-slate-600 leading-6">

              <p className="my-4">Wir freuen uns sehr über Ihr Interesse an unserem Unternehmen. Datenschutz hat einen besonders hohen Stellenwert für die Geschäftsleitung der AirClean VS.</p>
              <p className="my-4">Eine Nutzung der Internetseiten der AirClean VS ist grundsätzlich ohne jede Angabe personenbezogener Daten möglich. Sofern eine betroffene Person besondere Services unseres Unternehmens über unsere Internetseite in Anspruch nehmen möchte, könnte jedoch eine Verarbeitung personenbezogener Daten erforderlich werden. Ist die Verarbeitung personenbezogener Daten erforderlich und besteht für eine solche Verarbeitung keine gesetzliche Grundlage, holen wir generell eine Einwilligung der betroffenen Person ein.</p>
              <p className="my-4">Die Verarbeitung personenbezogener Daten, beispielsweise des Namens, der Anschrift, E-Mail-Adresse oder Telefonnummer einer betroffenen Person, erfolgt stets im Einklang mit der Datenschutz-Grundverordnung und in Übereinstimmung mit den für die AirClean VS geltenden landesspezifischen Datenschutzbestimmungen. Mittels dieser Datenschutzerklärung möchte unser Unternehmen die Öffentlichkeit über Art, Umfang und Zweck der von uns erhobenen, genutzten und verarbeiteten personenbezogenen Daten informieren. Ferner werden betroffene Personen mittels dieser Datenschutzerklärung über die ihnen zustehenden Rechte aufgeklärt.</p>
              <p className="my-4">Die AirClean VS hat als für die Verarbeitung Verantwortlicher zahlreiche technische und organisatorische Maßnahmen umgesetzt, um einen möglichst lückenlosen Schutz der über diese Internetseite verarbeiteten personenbezogenen Daten sicherzustellen. Dennoch können internetbasierte Datenübertragungen grundsätzlich Sicherheitslücken aufweisen, sodass ein absoluter Schutz nicht gewährleistet werden kann. Aus diesem Grund steht es jeder betroffenen Person frei, personenbezogene Daten auch auf alternativen Wegen, beispielsweise telefonisch, an uns zu übermitteln.</p>

              <h1 className="text-3xl font-bold text-slate-800 mt-10 mb-4">1. Begriffsbestimmungen</h1>
              <p className="my-4">Die Datenschutzerklärung der AirClean VS beruht auf den Begrifflichkeiten, die durch den Europäischen Richtlinien- und Verordnungsgeber beim Erlass der Datenschutz-Grundverordnung (DSGVO) verwendet wurden. Unsere Datenschutzerklärung soll sowohl für die Öffentlichkeit als auch für unsere Kunden und Geschäftspartner einfach lesbar und verständlich sein. Um dies zu gewährleisten, möchten wir vorab die verwendeten Begrifflichkeiten erläutern.</p>
              <p className="my-4">Wir verwenden in dieser Datenschutzerklärung unter anderem die folgenden Begriffe:</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">a) personenbezogene Daten</h2>
              <p className="my-4">Personenbezogene Daten sind alle Informationen, die sich auf eine identifizierte oder identifizierbare natürliche Person (im Folgenden „betroffene Person“) beziehen. Als identifizierbar wird eine natürliche Person angesehen, die direkt oder indirekt, insbesondere mittels Zuordnung zu einer Kennung wie einem Namen, zu einer Kennnummer, zu Standortdaten, zu einer Online-Kennung oder zu einem oder mehreren besonderen Merkmalen, die Ausdruck der physischen, physiologischen, genetischen, psychischen, wirtschaftlichen, kulturellen oder sozialen Identität dieser natürlichen Person sind, identifiziert werden kann.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">b) betroffene Person</h2>
              <p className="my-4">Betroffene Person ist jede identifizierte oder identifizierbare natürliche Person, deren personenbezogene Daten von dem für die Verarbeitung Verantwortlichen verarbeitet werden.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">c) Verarbeitung</h2>
              <p className="my-4">Verarbeitung ist jeder mit oder ohne Hilfe automatisierter Verfahren ausgeführte Vorgang oder jede solche Vorgangsreihe im Zusammenhang mit personenbezogenen Daten wie das Erheben, das Erfassen, die Organisation, das Ordnen, die Speicherung, die Anpassung oder Veränderung, das Auslesen, das Abfragen, die Verwendung, die Offenlegung durch Übermittlung, Verbreitung oder eine andere Form der Bereitstellung, den Abgleich oder die Verknüpfung, die Einschränkung, das Löschen oder die Vernichtung.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">d) Einschränkung der Verarbeitung</h2>
              <p className="my-4">Einschränkung der Verarbeitung ist die Markierung gespeicherter personenbezogener Daten mit dem Ziel, ihre künftige Verarbeitung einzuschränken.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">e) Profiling</h2>
              <p className="my-4">Profiling ist jede Art der automatisierten Verarbeitung personenbezogener Daten, die darin besteht, dass diese personenbezogenen Daten verwendet werden, um bestimmte persönliche Aspekte, die sich auf eine natürliche Person beziehen, zu bewerten, insbesondere, um Aspekte bezüglich Arbeitsleistung, wirtschaftlicher Lage, Gesundheit, persönlicher Vorlieben, Interessen, Zuverlässigkeit, Verhalten, Aufenthaltsort oder Ortswechsel dieser natürlichen Person zu analysieren oder vorherzusagen.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">f) Pseudonymisierung</h2>
              <p className="my-4">Pseudonymisierung ist die Verarbeitung personenbezogener Daten in einer Weise, auf welche die personenbezogenen Daten ohne Hinzuziehung zusätzlicher Informationen nicht mehr einer spezifischen betroffenen Person zugeordnet werden können, sofern diese zusätzlichen Informationen gesondert aufbewahrt werden und technischen und organisatorischen Maßnahmen unterliegen, die gewährleisten, dass die personenbezogenen Daten nicht einer identifizierten oder identifizierbaren natürlichen Person zugewiesen werden.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">g) Verantwortlicher oder für die Verarbeitung Verantwortlicher</h2>
              <p className="my-4">Verantwortlicher oder für die Verarbeitung Verantwortlicher ist die natürliche oder juristische Person, Behörde, Einrichtung oder andere Stelle, die allein oder gemeinsam mit anderen über die Zwecke und Mittel der Verarbeitung von personenbezogenen Daten entscheidet. Sind die Zwecke und Mittel dieser Verarbeitung durch das Unionsrecht oder das Recht der Mitgliedstaaten vorgegeben, so kann der Verantwortliche beziehungsweise können die bestimmten Kriterien seiner Benennung nach dem Unionsrecht oder dem Recht der Mitgliedstaaten vorgesehen werden.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">h) Auftragsverarbeiter</h2>
              <p className="my-4">Auftragsverarbeiter ist eine natürliche oder juristische Person, Behörde, Einrichtung oder andere Stelle, die personenbezogene Daten im Auftrag des Verantwortlichen verarbeitet.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">i) Empfänger</h2>
              <p className="my-4">Empfänger ist eine natürliche oder juristische Person, Behörde, Einrichtung oder andere Stelle, der personenbezogene Daten offengelegt werden, unabhängig davon, ob es sich bei ihr um einen Dritten handelt oder nicht. Behörden, die im Rahmen eines bestimmten Untersuchungsauftrags nach dem Unionsrecht oder dem Recht der Mitgliedstaaten möglicherweise personenbezogene Daten erhalten, gelten jedoch nicht als Empfänger.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">j) Dritter</h2>
              <p className="my-4">Dritter ist eine natürliche oder juristische Person, Behörde, Einrichtung oder andere Stelle außer der betroffenen Person, dem Verantwortlichen, dem Auftragsverarbeiter und den Personen, die unter der unmittelbaren Verantwortung des Verantwortlichen oder des Auftragsverarbeiters befugt sind, die personenbezogenen Daten zu verarbeiten.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">k) Einwilligung</h2>
              <p className="my-4">Einwilligung ist jede von der betroffenen Person freiwillig für den bestimmten Fall in informierter Weise und unmissverständlich abgegebene Willensbekundung in Form einer Erklärung oder einer sonstigen eindeutigen bestätigenden Handlung, mit der die betroffene Person zu verstehen gibt, dass sie mit der Verarbeitung der sie betreffenden personenbezogenen Daten einverstanden ist.</p>

              <h1 className="text-3xl font-bold text-slate-800 mt-10 mb-4">2. Name und Anschrift des für die Verarbeitung Verantwortlichen</h1>
              <p className="my-4">Verantwortlicher im Sinne der Datenschutz-Grundverordnung, sonstiger in den Mitgliedstaaten der Europäischen Union geltenden Datenschutzgesetze und anderer Bestimmungen mit datenschutzrechtlichem Charakter ist die:</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">AirClean VS</h2>
              <p className="my-4">
                Vertreten durch ihren Geschäftsführer<br />
                Herrn Viktor Selmanaj<br />
                Am Martinszehnten 3<br />
                60437 Frankfurt am Main
              </p>

              <h1 className="text-3xl font-bold text-slate-800 mt-10 mb-4">3. Cookies</h1>
              <p className="my-4">Die Internetseiten der AirClean VS verwenden Cookies. Cookies sind Textdateien, welche über einen Internetbrowser auf einem Computersystem abgelegt und gespeichert werden.</p>
              <p className="my-4">Zahlreiche Internetseiten und Server verwenden Cookies. Viele Cookies enthalten eine sogenannte Cookie-ID. Eine Cookie-ID ist eine eindeutige Kennung des Cookies. Sie besteht aus einer Zeichenfolge, durch welche Internetseiten und Server dem konkreten Internetbrowser zugeordnet werden können, in dem das Cookie gespeichert wurde. Dies ermöglicht es den besuchten Internetseiten und Servern, den individuellen Browser der betroffenen Person von anderen Internetbrowsern, die andere Cookies enthalten, zu unterscheiden. Ein bestimmter Internetbrowser kann über die eindeutige Cookie-ID wiedererkannt und identifiziert werden.</p>
              <p className="my-4">Durch den Einsatz von Cookies kann die AirClean VS den Nutzern dieser Internetseite nutzerfreundlichere Services bereitstellen, die ohne die Cookie-Setzung nicht möglich wären.</p>
              <p className="my-4">Mittels eines Cookies können die Informationen und Angebote auf unserer Internetseite im Sinne des Benutzers optimiert werden. Cookies ermöglichen uns, wie bereits erwähnt, die Benutzer unserer Internetseite wiederzuerkennen. Zweck dieser Wiedererkennung ist es, den Nutzern die Verwendung unserer Internetseite zu erleichtern. Der Benutzer einer Internetseite, die Cookies verwendet, muss beispielsweise nicht bei jedem Besuch der Internetseite erneut seine Zugangsdaten eingeben, weil dies von der Internetseite und dem auf dem Computersystem des Benutzers abgelegten Cookie übernommen wird. Ein weiteres Beispiel ist das Cookie eines Warenkorbes im Online-Shop. Der Online-Shop merkt sich die Artikel, die ein Kunde in den virtuellen Warenkorb gelegt hat, über ein Cookie.</p>
              <p className="my-4">Die betroffene Person kann die Setzung von Cookies durch unsere Internetseite jederzeit mittels einer entsprechenden Einstellung des genutzten Internetbrowsers verhindern und damit der Setzung von Cookies dauerhaft widersprechen. Ferner können bereits gesetzte Cookies jederzeit über einen Internetbrowser oder andere Softwareprogramme gelöscht werden. Dies ist in allen gängigen Internetbrowsern möglich. Deaktiviert die betroffene Person die Setzung von Cookies in dem genutzten Internetbrowser, sind unter Umständen nicht alle Funktionen unserer Internetseite vollumfänglich nutzbar.</p>

              <h1 className="text-3xl font-bold text-slate-800 mt-10 mb-4">4. Analyse Tools und Werbung</h1>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">Google Analytics</h2>
              <p className="my-4">Google Analytics ist ein Trackingtool des US-amerikanischen Unternehmens Google LLC, das der Datenverkehrsanalyse von Webseiten dient. Der Dienst untersucht u.&nbsp;a. die Herkunft der Besucher, ihre Verweildauer auf einzelnen Seiten sowie die Nutzung von Suchmaschinen und erlaubt damit eine bessere Erfolgskontrolle von Werbekampagnen.&nbsp;</p>
              <p className="my-4">Die Nutzung von Google Web Fonts erfolgt im Interesse einer einheitlichen und ansprechenden Darstellung unserer Online-Angebote. Dies stellt ein berechtigtes Interesse im Sinne von Art. 6 Abs. 1 lit. f DSGVO dar.</p>
              <p className="my-4">Mehr Informationen zum Umgang mit Nutzerdaten finden Sie in der Datenschutzerklärung von Google:&nbsp;<a href="https://www.google.de/intl/de/policies/privacy/" target="_blank" rel="noreferrer"></a><a href="https://www.google.de/intl/de/policies/privacy/" target="_blank" rel="noreferrer">https://www.google.de/intl/de/policies/privacy/</a>.</p>

              <h1 className="text-3xl font-bold text-slate-800 mt-10 mb-4">5. Plugins und Tools</h1>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">Usercentrics für das Consent-Management</h2>
              <p className="my-4">Diese Website nutzt die Consent Management Plattform (CMP) von Usercentrics, um Ihre Einwilligung zur Speicherung von Cookies auf Ihrem Endgerät einzuholen und diese datenschutzkonform zu dokumentieren.&nbsp;Die Usercentrics Consent Management Plattform sammelt Logfile- und Einwilligungsdaten mittels JavaScript. Dieses JavaScript ermöglicht es, den Nutzer über seine Einwilligung zu bestimmten Tags auf unserer Website zu informieren und diese einzuholen, zu verwalten und zu dokumentieren.&nbsp;</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">Webanalyse via etracker</h2>
              <p className="my-4">Der Anbieter dieser Website nutzt Dienste der etracker GmbH aus Hamburg, Deutschland (<a href="http://www.etracker.com/" target="_blank" rel="noreferrer">www.etracker.com</a>) zur Analyse von Nutzungsdaten. Wir verwenden standardmäßig keine Cookies für die Webanalyse. Soweit wir Analyse- und Optimierungs-Cookies einsetzen, holen wir Ihre explizite Einwilligung gesondert im Vorfeld ein. Ist das der Fall und Sie stimmen zu, werden Cookies eingesetzt, die eine statistische Reichweiten-Analyse dieser Website, eine Erfolgsmessung unserer Online-Marketing-Maßnahmen sowie Testverfahren ermöglichen, um z.&nbsp;B. unterschiedliche Versionen unseres Online-Angebotes oder seiner Bestandteile zu testen und zu optimieren. Cookies sind kleine Textdateien, die vom Internet Browser auf dem Endgerät des Nutzers gespeichert werden. etracker Cookies enthalten keine Informationen, die eine Identifikation eines Nutzers ermöglichen.</p>
              <p className="my-4">Die mit etracker erzeugten Daten werden im Auftrag des Anbieters dieser Website von etracker ausschließlich in Deutschland verarbeitet und gespeichert und unterliegen damit den strengen deutschen und europäischen Datenschutzgesetzen und -standards. etracker wurde diesbezüglich unabhängig geprüft, zertifiziert und mit dem Datenschutz-Gütesiegel ePrivacyseal ausgezeichnet.</p>
              <p className="my-4">Die Datenverarbeitung erfolgt auf Basis der gesetzlichen Bestimmungen des Art. 6 Abs. 1 lit. f (berechtigtes Interesse) der Datenschutzgrundverordnung (DSGVO). Unser Anliegen im Sinne der DSGVO (berechtigtes Interesse) ist die Optimierung unseres Online-Angebotes und unseres Webauftritts. Da uns die Privatsphäre unserer Besucher wichtig ist, werden die Daten, die möglicherweise einen Bezug zu einer einzelnen Person zulassen, wie die IP-Adresse, Anmelde- oder Gerätekennungen, frühestmöglich anonymisiert oder pseudonymisiert. Eine andere Verwendung, Zusammenführung mit anderen Daten oder eine Weitergabe an Dritte erfolgt nicht.</p>
              <p className="my-4">Sie können der vorbeschriebenen Datenverarbeitung jederzeit widersprechen. Der Widerspruch hat keine nachteiligen Folgen.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">Google Web Fonts</h2>
              <p className="my-4">Diese Seite nutzt zur einheitlichen Darstellung von Schriftarten sogenannte Web Fonts, die von Google bereitgestellt werden. Beim Aufruf einer Seite lädt Ihr Browser die benötigten Web-Fonts in ihren Browsercache, um Texte und Schriftarten korrekt anzuzeigen.</p>
              <p className="my-4">Zu diesem Zweck muss der von Ihnen verwendete Browser Verbindung zu den Servern von Google aufnehmen. Hierdurch erlangt Google Kenntnis darüber, dass über Ihre IP-Adresse unsere Website aufgerufen wurde.</p>
              <p className="my-4">Die Nutzung von Google Web Fonts erfolgt im Interesse einer einheitlichen und ansprechenden Darstellung unserer Online-Angebote. Dies stellt ein berechtigtes Interesse im Sinne von Art. 6 Abs. 1 lit. f DSGVO dar.</p>
              <p className="my-4">Wenn Ihr Browser Web Fonts nicht unterstützt, wird eine Standardschrift von Ihrem Computer genutzt.</p>
              <p className="my-4">Weitere Informationen zu Google Web Fonts finden Sie unter&nbsp;<a href="https://developers.google.com/fonts/faq" target="_blank" rel="noreferrer"></a><a href="https://developers.google.com/fonts/faq" target="_blank" rel="noreferrer">https://developers.google.com/fonts/faq</a>&nbsp;und in der Datenschutzerklärung von Google:&nbsp;<a href="https://www.google.com/policies/privacy/" target="_blank" rel="noreferrer"></a><a href="https://www.google.com/policies/privacy/" target="_blank" rel="noreferrer">https://www.google.com/policies/privacy/</a>.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">Google Tag Manager</h2>
              <p className="my-4">Wir verwenden den Dienst namens Google Tag Manager von Google. „Google“ ist eine Firmengruppe und besteht aus den Firmen Google Irland Ltd. (Anbieter des Dienstes), Gordon House, Barrow Street, Dublin 4, Irland sowie Google LLC, 1600 Amphitheater Parkway, Mountain View, CA 94043, USA sowie andere verbundene Unternehmen der Google LLC.</p>
              <p className="my-4">Wir haben einen Auftragsverarbeitungsvertrag mit Google abgeschlossen. Der Google Tag Manager ist ein Hilfsdienst und verarbeitet selbst personenbezogenen Daten nur zu technisch notwendigen Zwecken. Der Google Tag Manager sorgt für das Laden anderer Komponenten, die ihrerseits unter Umständen Daten erfassen. Der Google Tag Manager greift nicht auf diese Daten zu.</p>
              <p className="my-4">Weitere Informationen zum Google Tag Manager finden Sie in den Datenschutzbestimmungen von Google.</p>
              <p className="my-4">Bitte beachten Sie, dass amerikanische Behörden, etwa Geheimdienste, aufgrund amerikanischer Gesetze wie dem Cloud-Act möglicherweise Zugriff auf personenbezogene Daten erhalten könnten, die beim Einbinden dieses Dienstes zwangsläufig aufgrund des Internet-Protokolls (TCP) mit Google ausgetauscht werden.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">Google Ads Conversion-Tracking</h2>
              <p className="my-4">Wir verwenden auf unserer Website das Online-Werbeprogramm „Google Ads“ und in diesem Rahmen Conversion-Tracking (Besuchsaktionsauswertung). Das Google Conversion Tracking ist ein Analysedienst der Google LLC (1600 Amphitheatre Parkway, Mountain View, CA 94043, USA; „Google“). Soweit Sie Ihren gewöhnlichen Aufenthalt im Europäischen Wirtschaftsraum oder der Schweiz haben, ist Google Irland Limited (Gordon House, Barrow Street, Dublin 4, Irland) der für Ihre Daten zuständige Verantwortliche. Google Irland Limited ist demnach das mit Google verbundene Unternehmen, welches für die Verarbeitung Ihrer Daten und die Einhaltung der anwendbaren Datenschutzgesetze verantwortlich ist.</p>
              <p className="my-4">Wenn Sie auf eine von Google geschaltete Anzeige klicken, wird ein Cookie für das Conversion-Tracking auf Ihrem Rechner abgelegt. Diese Cookies haben eine begrenzte Gültigkeit, enthalten keine personenbezogenen Daten und dienen somit nicht der persönlichen Identifizierung. Wenn Sie bestimmte Seiten unserer Website besuchen und das Cookie noch nicht abgelaufen ist, können Google und wir erkennen, dass Sie auf die Anzeige geklickt haben und zu dieser Seite weitergeleitet wurden. Jeder Google Ads-Kunde erhält ein anderes Cookie. Somit besteht keine Möglichkeit, dass Cookies über die Websites von Ads-Kunden nachverfolgt werden können.</p>
              <p className="my-4">Die Informationen, die mithilfe des Conversion-Cookies eingeholt werden, dienen dem Zweck, Conversion-Statistiken zu erstellen. Hierbei erfahren wir die Gesamtanzahl der Nutzer, die auf eine unserer Anzeigen geklickt haben und zu einer mit einem Conversion-Tracking-Tag versehenen Seite weitergeleitet wurden. Wir erhalten jedoch keine Informationen, mit denen sich Nutzer persönlich identifizieren lassen.</p>
              <p className="my-4">Ihre Daten werden gegebenenfalls in die USA übermittelt. Für die USA ist kein Angemessenheitsbeschluss der EU-Kommission vorhanden. Die Datenübermittlung erfolgt u.a auf Grundlage von Standardvertragsklauseln als geeignete Garantien für den Schutz der personenbezogenen Daten, einsehbar unter:&nbsp;<a href="https://policies.google.com/privacy/frameworks" target="_blank" rel="noreferrer"></a><a href="https://policies.google.com/privacy/frameworks" target="_blank" rel="noreferrer">https://policies.google.com/privacy/frameworks</a>&nbsp;und&nbsp;<a href="https://business.safety.google/adscontrollerterms/" target="_blank" rel="noreferrer"></a><a href="https://business.safety.google/adscontrollerterms/" target="_blank" rel="noreferrer">https://business.safety.google/adscontrollerterms/</a>.</p>
              <p className="my-4">Die Nutzung von Cookies oder vergleichbarer Technologien erfolgt mit Ihrer Einwilligung auf Grundlage des §&nbsp;25 Abs. 1 S. 1 TTDSG i.V.m. Art. 6 Abs. 1 lit. a DSGVO. Die Verarbeitung Ihrer personenbezogenen Daten erfolgt mit Ihrer Einwilligung auf Grundlage des Art. 6 Abs. 1 lit. a DSGVO. Sie können die Einwilligung jederzeit widerrufen, ohne dass die Rechtmäßigkeit der aufgrund der Einwilligung bis zum Widerruf erfolgten Verarbeitung berührt wird.</p>
              <p className="my-4">Nähere Informationen sowie die Datenschutzerklärung von Google finden Sie unter:&nbsp;<a href="https://www.google.de/policies/privacy/" target="_blank" rel="noreferrer"></a><a href="https://www.google.de/policies/privacy/" target="_blank" rel="noreferrer">https://www.google.de/policies/privacy/</a></p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">Google Maps</h2>
              <p className="my-4">Diese Seite nutzt über eine API den Kartendienst Google Maps. Anbieter ist die Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA.</p>
              <p className="my-4">Zur Nutzung der Funktionen von Google Maps ist es notwendig, Ihre IP-Adresse zu speichern. Diese Informationen werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert. Der Anbieter dieser Seite hat keinen Einfluss auf diese Datenübertragung.</p>
              <p className="my-4">Die Nutzung von Google Maps erfolgt im Interesse einer ansprechenden Darstellung unserer Online-Angebote und an einer leichten Auffindbarkeit der von uns auf der Website angegebenen Orte. Dies stellt ein berechtigtes Interesse im Sinne von Art. 6 Abs. 1 lit. f DSGVO dar.</p>
              <p className="my-4">Mehr Informationen zum Umgang mit Nutzerdaten finden Sie in der Datenschutzerklärung von Google:&nbsp;<a href="https://www.google.de/intl/de/policies/privacy/" target="_blank" rel="noreferrer"></a><a href="https://www.google.de/intl/de/policies/privacy/" target="_blank" rel="noreferrer">https://www.google.de/intl/de/policies/privacy/</a>&nbsp;.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">LinkedIn Insight Tag</h2>
              <p className="my-4">Unsere Website nutzt das LinkedIn Insight Conversion Tool der LinkedIn Corporation, 2029 Stierlin Court, Mountain View, CA 94043, USA. Im Falle einer ausdrücklichen Einwilligung kann hierdurch das Verhalten von Nutzern nachverfolgt werden, nachdem diese eine Werbeanzeige auf LinkedIn gesehen oder angeklickt haben. Dieses Verfahren dient dazu, die Wirksamkeit der Werbeanzeigen auf LinkedIn für statistische und Marktforschungszwecke auszuwerten und kann dazu beitragen, zukünftige Werbemaßnahmen zu optimieren. Dazu wird in Ihrem Browser ein Cookie mit einer Gültigkeit von 120 Tagen gesetzt, welches LinkedIn ermöglicht, Sie wiederzuerkennen, wenn Sie eine Webseite besuchen. LinkedIn verwendet diese Daten, um für uns anonyme Berichte zu Anzeigenaktivitäten und Informationen darüber, wie Sie mit unserer Website interagieren, zu erstellen.</p>
              <p className="my-4">Die erhobenen Daten sind für uns anonym, bieten uns also keine Rückschlüsse auf die Identität der Nutzer. Allerdings werden die Daten von LinkedIn gespeichert und verarbeitet, sodass eine Verbindung zum jeweiligen Nutzerprofil möglich ist und LinkedIn die Daten für eigene Werbezwecke, entsprechend der LinkedIn-Datenverwendungsrichtlinie (<a href="https://www.linkedin.com/legal/privacy-policy?trk=hb_ft_priv" target="_blank" rel="noreferrer"></a><a href="https://www.linkedin.com/legal/privacy-policy?trk=hb_ft_priv" target="_blank" rel="noreferrer">https://www.linkedin.com/legal/privacy-policy?trk=hb_ft_priv</a>) verwenden kann. Sie können LinkedIn sowie dessen Partnern das Schalten von Werbeanzeigen außerhalb von LinkedIn ermöglichen. Es kann ferner zu diesen Zwecken ein Cookie auf Ihrem Rechner gespeichert werden. Diese Verarbeitungsvorgänge erfolgen ausschließlich bei Erteilung der ausdrücklichen Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO.</p>
              <p className="my-4">Das LinkedIn Insight Conversion Tool sowie der interessenbasierten Werbung können Sie durch Opt-Out unter folgendem Link deaktivieren:&nbsp;<a href="https://www.linkedin.com/psettings/guest-controls/retargeting-opt-out" target="_blank" rel="noreferrer"></a><a href="https://www.linkedin.com/psettings/guest-controls/retargeting-opt-out" target="_blank" rel="noreferrer">https://www.linkedin.com/psettings/guest-controls/retargeting-opt-out</a></p>
              <p className="my-4">Wenn Sie LinkedIn-Mitglied sind, klicken Sie dazu auf das Feld „Auf LinkedIn ablehnen“. Sonstige Besucher klicken auf „Ablehnen“.</p>
              <p className="my-4">Weitere Informationen zum Datenschutz bei LinkedIn finden Sie hier:&nbsp;<a href="https://sb-clean.de/datenschutzerklaerung/#choices-oblig"></a><a href="https://www.linkedin.com/legal/privacy-policy#choices-oblig" target="_blank" rel="noreferrer">https://www.linkedin.com/legal/privacy-policy#choices-oblig</a></p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">Informationspflichten bei Erhebung personenbezogener Daten insbesondere beim Bewerbungsprozess (Art. 13, 14 DSGVO)</h2>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">Zweck der Datenverarbeitung</h2>
              <p className="my-4">Wir speichern alle uns zur Verfügung gestellten Informationen von Personen, die sich für eine Tätigkeit in unserem Unternehmen bewerben. Dies gilt sowohl für Bewerbungen auf konkrete Ausschreibungen als auch für Initiativbewerbungen. Die Speicherdauer beträgt maximal sechs Monate. Innerhalb dieser Zeit wird die Bewerbung geprüft und die Informationen stehen bis zum Ablauf der Speicherdauer zur Verfügung, auch um spätere Anfragen (z.&nbsp;B. Anforderung von Unterlagen, Absagen etc.) qualifiziert beantworten zu können. Im Rahmen von Bewerbungsverfahren erfolgen keine Datenerhebungen bei Dritten, es sei denn, es liegt eine Einwilligung Betroffener vor. Es erfolgt kein Datentransfer an Dritte, insbesondere auch nicht in ein anderes Land.</p>
              <p className="my-4">Führt die Bewerbung zur Begründung eines Ausbildungs- oder Arbeitsverhältnisses, werden die Daten zehn Jahre gespeichert, sofern nicht andere Vorschriften längere Aufbewahrungsfristen vorschreiben. Bewerber sind dann verpflichtet, Daten zur Begründung eines Arbeitsverhältnisses zu ergänzen, z.&nbsp;B. Sozialversicherungsdaten. In der Folge findet eine Datenübermittlung mit Sozialversicherungsträgern und dem Finanzamt statt.</p>
              <p className="my-4">Rechtsgrundlagen für die Datenerhebung sind Art. 6 Abs. 1 Ziff. f DSGVO und § 26 Abs. 1 BDSG-neu sowie weitere gesetzliche Vorgaben, aus denen sich im Falle der Begründung von Arbeitsverhältnissen Speicherobliegenheiten ergeben, z. B. § 147 AO, § 257 HGB, § 35 Abs. 1 SRVwV etc.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">Rechte Betroffener</h2>
              <p className="my-4">Bewerberinnen und Bewerber haben auf der Basis von Art. 13, 14 DSGVO jederzeit das Recht auf Auskunft über die sie betreffenden personenbezogenen Daten und in der Folge gegebenenfalls das weitere Recht auf Berichtigung oder Löschung oder auf Einschränkung der Verarbeitung. Insbesondere besteht das jederzeitige Recht, gespeicherte Daten zu löschen. Ein Löschungswunsch führt zu einer Beendigung des Bewerbungsverfahrens und es können in der Folge keine Auskünfte mehr zum Verfahrensablauf erteilt werden.</p>
              <p className="my-4">Nach Begründung eines Arbeitsverhältnisses reduziert sich das Recht zur Datenlöschung oder Einschränkung der Verarbeitung. Gesetzliche und/oder vertragliche Regelungen zur Dokumentation und Archivierung genießen Vorrang vor Löschungswünschen. Zur Wahrnehmung der Rechte können sich Betroffene an die oben genannten Verantwortlichen im Unternehmen, den betrieblichen Datenschutzbeauftragten oder die Aufsichtsbehörde wenden.</p>

              <h1 className="text-3xl font-bold text-slate-800 mt-10 mb-4">6. Erfassung von allgemeinen Daten und Informationen</h1>
              <p className="my-4">Die Internetseite der AirClean VS erfasst mit jedem Aufruf der Internetseite durch eine betroffene Person oder ein automatisiertes System eine Reihe von allgemeinen Daten und Informationen. Diese allgemeinen Daten und Informationen werden in den Logfiles des Servers gespeichert. Erfasst werden können die (1) verwendeten Browsertypen und Versionen, (2) das vom zugreifenden System verwendete Betriebssystem, (3) die Internetseite, von welcher ein zugreifendes System auf unsere Internetseite gelangt (sogenannte Referrer), (4) die Unterwebseiten, welche über ein zugreifendes System auf unserer Internetseite angesteuert werden, (5) das Datum und die Uhrzeit eines Zugriffs auf die Internetseite, (6) eine Internet-Protokoll-Adresse (IP-Adresse), (7) der Internet-Service-Provider des zugreifenden Systems und (8) sonstige ähnliche Daten und Informationen, die der Gefahrenabwehr im Falle von Angriffen auf unsere informationstechnologischen Systeme dienen.</p>
              <p className="my-4">Bei der Nutzung dieser allgemeinen Daten und Informationen zieht die AirClean VS keine Rückschlüsse auf die betroffene Person. Diese Informationen werden vielmehr benötigt, um (1) die Inhalte unserer Internetseite korrekt auszuliefern, (2) die Inhalte unserer Internetseite sowie die Werbung für diese zu optimieren, (3) die dauerhafte Funktionsfähigkeit unserer informationstechnologischen Systeme und der Technik unserer Internetseite zu gewährleisten sowie (4) um Strafverfolgungsbehörden im Falle eines Cyberangriffes die zur Strafverfolgung notwendigen Informationen bereitzustellen. Diese anonym erhobenen Daten und Informationen werden durch AirClean VS daher einerseits statistisch und ferner mit dem Ziel ausgewertet, den Datenschutz und die Datensicherheit in unserem Unternehmen zu erhöhen, um letztlich ein optimales Schutzniveau für die von uns verarbeiteten personenbezogenen Daten sicherzustellen. Die anonymen Daten der Server-Logfiles werden getrennt von allen durch eine betroffene Person angegebenen personenbezogenen Daten gespeichert.</p>

              <h1 className="text-3xl font-bold text-slate-800 mt-10 mb-4">7. Kontaktmöglichkeit über die Internetseite</h1>
              <p className="my-4">Die Internetseite der AirClean VS enthält aufgrund von gesetzlichen Vorschriften Angaben, die eine schnelle elektronische Kontaktaufnahme zu unserem Unternehmen sowie eine unmittelbare Kommunikation mit uns ermöglichen, was ebenfalls eine allgemeine Adresse der sogenannten elektronischen Post (E-Mail-Adresse) umfasst. Sofern eine betroffene Person per E-Mail oder über ein Kontaktformular den Kontakt mit dem für die Verarbeitung Verantwortlichen aufnimmt, werden die von der betroffenen Person übermittelten personenbezogenen Daten automatisch gespeichert. Solche auf freiwilliger Basis von einer betroffenen Person an den für die Verarbeitung Verantwortlichen übermittelten personenbezogenen Daten werden für Zwecke der Bearbeitung oder der Kontaktaufnahme zur betroffenen Person gespeichert. Es erfolgt keine Weitergabe dieser personenbezogenen Daten an Dritte.</p>

              <h1 className="text-3xl font-bold text-slate-800 mt-10 mb-4">8. Routinemäßige Löschung und Sperrung von personenbezogenen Daten</h1>
              <p className="my-4">Der für die Verarbeitung Verantwortliche verarbeitet und speichert personenbezogene Daten der betroffenen Person nur für den Zeitraum, der zur Erreichung des Speicherungszwecks erforderlich ist oder sofern dies durch den Europäischen Richtlinien- und Verordnungsgeber oder einen anderen Gesetzgeber in Gesetzen oder Vorschriften, welchen der für die Verarbeitung Verantwortliche unterliegt, vorgesehen wurde.</p>
              <p className="my-4">Entfällt der Speicherungszweck oder läuft eine vom Europäischen Richtlinien- und Verordnungsgeber oder einem anderen zuständigen Gesetzgeber vorgeschriebene Speicherfrist ab, werden die personenbezogenen Daten routinemäßig und entsprechend den gesetzlichen Vorschriften gesperrt oder gelöscht.</p>

              <h1 className="text-3xl font-bold text-slate-800 mt-10 mb-4">9. Rechte der betroffenen Person</h1>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">a) Recht auf Bestätigung</h2>
              <p className="my-4">Jede betroffene Person hat das vom Europäischen Richtlinien- und Verordnungsgeber eingeräumte Recht, von dem für die Verarbeitung Verantwortlichen eine Bestätigung darüber zu verlangen, ob sie betreffende personenbezogene Daten verarbeitet werden. Möchte eine betroffene Person dieses Bestätigungsrecht in Anspruch nehmen, kann sie sich hierzu jederzeit an einen Mitarbeiter des für die Verarbeitung Verantwortlichen wenden.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">b) Recht auf Auskunft</h2>
              <p className="my-4">Jede von der Verarbeitung personenbezogener Daten betroffene Person hat das vom Europäischen Richtlinien- und Verordnungsgeber gewährte Recht, jederzeit von dem für die Verarbeitung Verantwortlichen unentgeltliche Auskunft über die zu seiner Person gespeicherten personenbezogenen Daten und eine Kopie dieser Auskunft zu erhalten. Ferner hat der Europäische Richtlinien- und Verordnungsgeber der betroffenen Person Auskunft über folgende Informationen zugestanden:</p>
              <ul>
                <li>die Verarbeitungszwecke</li>
                <li>die Kategorien personenbezogener Daten, die verarbeitet werden</li>
                <li>die Empfänger oder Kategorien von Empfängern, gegenüber denen die personenbezogenen Daten offengelegt worden sind oder noch offengelegt werden, insbesondere bei Empfängern in Drittländern oder bei internationalen Organisationen</li>
                <li>falls möglich die geplante Dauer, für die die personenbezogenen Daten gespeichert werden, oder, falls dies nicht möglich ist, die Kriterien für die Festlegung dieser Dauer</li>
                <li>das Bestehen eines Rechts auf Berichtigung oder Löschung der sie betreffenden personenbezogenen Daten oder auf Einschränkung der Verarbeitung durch den Verantwortlichen oder eines Widerspruchsrechts gegen diese Verarbeitung</li>
                <li>das Bestehen eines Beschwerderechts bei einer Aufsichtsbehörde</li>
                <li>wenn die personenbezogenen Daten nicht bei der betroffenen Person erhoben werden: Alle verfügbaren Informationen über die Herkunft der Daten</li>
                <li>das Bestehen einer automatisierten Entscheidungsfindung einschließlich Profiling gemäß Artikel 22 Abs.1 und 4 DSGVO und — zumindest in diesen Fällen — aussagekräftige Informationen über die involvierte Logik sowie die Tragweite und die angestrebten Auswirkungen einer derartigen Verarbeitung für die betroffene Person</li>
              </ul>
              <p className="my-4">Ferner steht der betroffenen Person ein Auskunftsrecht darüber zu, ob personenbezogene Daten an ein Drittland oder an eine internationale Organisation übermittelt wurden. Sofern dies der Fall ist, so steht der betroffenen Person im Übrigen das Recht zu, Auskunft über die geeigneten Garantien im Zusammenhang mit der Übermittlung zu erhalten.</p>
              <p className="my-4">Möchte eine betroffene Person dieses Auskunftsrecht in Anspruch nehmen, kann sie sich hierzu jederzeit an einen Mitarbeiter des für die Verarbeitung Verantwortlichen wenden,</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">c) Recht auf Berichtigung</h2>
              <p className="my-4">Jede von der Verarbeitung personenbezogener Daten betroffene Person hat das vom Europäischen Richtlinien- und Verordnungsgeber gewährte Recht, die unverzügliche Berichtigung sie betreffender unrichtiger personenbezogener Daten zu verlangen. Ferner steht der betroffenen Person das Recht zu, unter Berücksichtigung der Zwecke der Verarbeitung, die Vervollständigung unvollständiger personenbezogener Daten – auch mittels einer ergänzenden Erklärung – zu verlangen.</p>
              <p className="my-4">Möchte eine betroffene Person dieses Berichtigungsrecht in Anspruch nehmen, kann sie sich hierzu jederzeit an einen Mitarbeiter des für die Verarbeitung Verantwortlichen wenden.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">d) Recht auf Löschung (Recht auf Vergessen werden)</h2>
              <p className="my-4">Jede von der Verarbeitung personenbezogener Daten betroffene Person hat das vom Europäischen Richtlinien- und Verordnungsgeber gewährte Recht, von dem Verantwortlichen zu verlangen, dass die sie betreffenden personenbezogenen Daten unverzüglich gelöscht werden, sofern einer der folgenden Gründe zutrifft und soweit die Verarbeitung nicht erforderlich ist:</p>
              <ul>
                <li>Die personenbezogenen Daten wurden für solche Zwecke erhoben oder auf sonstige Weise verarbeitet, für welche sie nicht mehr notwendig sind.</li>
                <li>Die betroffene Person widerruft ihre Einwilligung, auf die sich die Verarbeitung gemäß Art. 6 Abs. 1 Buchstabe a DSGVO oder Art. 9 Abs. 2 Buchstabe a DSGVO stützte, und es fehlt an einer anderweitigen Rechtsgrundlage für die Verarbeitung.</li>
                <li>Die betroffene Person legt gemäß Art. 21 Abs. 1 DSGVO Widerspruch gegen die Verarbeitung ein, und es liegen keine vorrangigen berechtigten Gründe für die Verarbeitung vor, oder die betroffene Person legt gemäß Art. 21 Abs. 2 DSGVO Widerspruch gegen die Verarbeitung ein.</li>
                <li>Die personenbezogenen Daten wurden unrechtmäßig verarbeitet.</li>
                <li>Die Löschung der personenbezogenen Daten ist zur Erfüllung einer rechtlichen Verpflichtung nach dem Unionsrecht oder dem Recht der Mitgliedstaaten erforderlich, dem der Verantwortliche unterliegt.</li>
                <li>Die personenbezogenen Daten wurden in Bezug auf angebotene Dienste der Informationsgesellschaft gemäß Art. 8 Abs. 1 DSGVO erhoben.</li>
              </ul>
              <p className="my-4">Sofern einer der oben genannten Gründe zutrifft und eine betroffene Person die Löschung von personenbezogenen Daten, die bei der AirClean VS gespeichert sind, veranlassen möchte, kann sie sich hierzu jederzeit an einen Mitarbeiter des für die Verarbeitung Verantwortlichen wenden. Der Mitarbeiter der AirClean VS wird veranlassen, dass dem Löschverlangen unverzüglich nachgekommen wird.</p>
              <p className="my-4">Wurden die personenbezogenen Daten von der AirClean VS öffentlich gemacht und ist unser Unternehmen als Verantwortlicher gemäß Art. 17 Abs. 1 DSGVO zur Löschung der personenbezogenen Daten verpflichtet, so trifft die AirClean VS unter Berücksichtigung der verfügbaren Technologie und der Implementierungskosten angemessene Maßnahmen, auch technischer Art, um andere für die Datenverarbeitung Verantwortliche, welche die veröffentlichten personenbezogenen Daten verarbeiten, darüber in Kenntnis zu setzen, dass die betroffene Person von diesen anderen für die Datenverarbeitung Verantwortlichen die Löschung sämtlicher Links zu diesen personenbezogenen Daten oder von Kopien oder Replikationen dieser personenbezogenen Daten verlangt hat, soweit die Verarbeitung nicht erforderlich ist. Der Mitarbeiter der AirClean VS wird im Einzelfall das Notwendige veranlassen.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">e) Recht auf Einschränkung der Verarbeitung</h2>
              <p className="my-4">Jede von der Verarbeitung personenbezogener Daten betroffene Person hat das vom Europäischen Richtlinien- und Verordnungsgeber gewährte Recht, von dem Verantwortlichen die Einschränkung der Verarbeitung zu verlangen, wenn eine der folgenden Voraussetzungen gegeben ist:</p>
              <ul>
                <li>Die Richtigkeit der personenbezogenen Daten wird von der betroffenen Person bestritten, und zwar für eine Dauer, die es dem Verantwortlichen ermöglicht, die Richtigkeit der personenbezogenen Daten zu überprüfen.</li>
                <li>Die Verarbeitung ist unrechtmäßig, die betroffene Person lehnt die Löschung der personenbezogenen Daten ab und verlangt stattdessen die Einschränkung der Nutzung der personenbezogenen Daten.</li>
                <li>Der Verantwortliche benötigt die personenbezogenen Daten für die Zwecke der Verarbeitung nicht länger, die betroffene Person benötigt sie jedoch zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen.</li>
                <li>Die betroffene Person hat Widerspruch gegen die Verarbeitung gem. Art. 21 Abs. 1 DSGVO eingelegt und es steht noch nicht fest, ob die berechtigten Gründe des Verantwortlichen gegenüber denen der betroffenen Person überwiegen.</li>
              </ul>
              <p className="my-4">Sofern eine der oben genannten Voraussetzungen gegeben ist und eine betroffene Person die Einschränkung von personenbezogenen Daten, die bei der AirClean VS gespeichert sind, verlangen möchte, kann sie sich hierzu jederzeit an einen Mitarbeiter des für die Verarbeitung Verantwortlichen wenden. Der Mitarbeiter AirClean VS wird die Einschränkung der Verarbeitung veranlassen.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">f) Recht auf Datenübertragbarkeit</h2>
              <p className="my-4">Jede von der Verarbeitung personenbezogener Daten betroffene Person hat das vom Europäischen Richtlinien- und Verordnungsgeber gewährte Recht, die sie betreffenden personenbezogenen Daten, welche durch die betroffene Person einem Verantwortlichen bereitgestellt wurden, in einem strukturierten, gängigen und maschinenlesbaren Format zu erhalten. Sie hat außerdem das Recht, diese Daten einem anderen Verantwortlichen ohne Behinderung durch den Verantwortlichen, dem die personenbezogenen Daten bereitgestellt wurden, zu übermitteln, sofern die Verarbeitung auf der Einwilligung gemäß Art. 6 Abs. 1 Buchstabe a DSGVO oder Art. 9 Abs. 2 Buchstabe a DSGVO oder auf einem Vertrag gemäß Art. 6 Abs. 1 Buchstabe b DSGVO beruht und die Verarbeitung mithilfe automatisierter Verfahren erfolgt, sofern die Verarbeitung nicht für die Wahrnehmung einer Aufgabe erforderlich ist, die im öffentlichen Interesse liegt oder in Ausübung öffentlicher Gewalt erfolgt, welche dem Verantwortlichen übertragen wurde.</p>
              <p className="my-4">Ferner hat die betroffene Person bei der Ausübung ihres Rechts auf Datenübertragbarkeit gemäß Art. 20 Abs. 1 DSGVO das Recht, zu erwirken, dass die personenbezogenen Daten direkt von einem Verantwortlichen an einen anderen Verantwortlichen übermittelt werden, soweit dies technisch machbar ist und sofern hiervon nicht die Rechte und Freiheiten anderer Personen beeinträchtigt werden.</p>
              <p className="my-4">Zur Geltendmachung des Rechts auf Datenübertragbarkeit kann sich die betroffene Person jederzeit an einen Mitarbeiter der AirClean VS wenden.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">g) Recht auf Widerspruch</h2>
              <p className="my-4">Jede von der Verarbeitung personenbezogener Daten betroffene Person hat das vom Europäischen Richtlinien- und Verordnungsgeber gewährte Recht, aus Gründen, die sich aus ihrer besonderen Situation ergeben, jederzeit gegen die Verarbeitung sie betreffender personenbezogener Daten, die aufgrund von Art. 6 Abs. 1 Buchstaben e oder f DSGVO erfolgt, Widerspruch einzulegen. Dies gilt auch für ein auf diese Bestimmungen gestütztes Profiling.</p><p className="my-4">Die AirClean VS verarbeitet die personenbezogenen Daten im Falle des Widerspruchs nicht mehr, es sei denn, wir können zwingende schutzwürdige Gründe für die Verarbeitung nachweisen, die den Interessen, Rechten und Freiheiten der betroffenen Person überwiegen, oder die Verarbeitung dient der Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen.</p>
              <p className="my-4">Verarbeitet die AirClean VS personenbezogene Daten, um Direktwerbung zu betreiben, so hat die betroffene Person das Recht, jederzeit Widerspruch gegen die Verarbeitung der personenbezogenen Daten zum Zwecke derartiger Werbung einzulegen. Dies gilt auch für das Profiling, soweit es mit solcher Direktwerbung in Verbindung steht. Widerspricht die betroffene Person gegenüber der AirClean VS der Verarbeitung für Zwecke der Direktwerbung, so wird die AirClean VS die personenbezogenen Daten nicht mehr für diese Zwecke verarbeiten.</p>
              <p className="my-4">Zudem hat die betroffene Person das Recht, aus Gründen, die sich aus ihrer besonderen Situation ergeben, gegen die sie betreffende Verarbeitung personenbezogener Daten, die bei der AirClean VS zu wissenschaftlichen oder historischen Forschungszwecken oder zu statistischen Zwecken gemäß Art. 89 Abs. 1 DSGVO erfolgen, Widerspruch einzulegen, es sei denn, eine solche Verarbeitung ist zur Erfüllung einer im öffentlichen Interesse liegenden Aufgabe erforderlich.</p>
              <p className="my-4">Zur Ausübung des Rechts auf Widerspruch kann sich die betroffene Person direkt jeden Mitarbeiter der AirClean VS oder einen anderen Mitarbeiter wenden. Der betroffenen Person steht es ferner frei, im Zusammenhang mit der Nutzung von Diensten der Informationsgesellschaft, ungeachtet der Richtlinie 2002/58/EG, ihr Widerspruchsrecht mittels automatisierter Verfahren auszuüben, bei denen technische Spezifikationen verwendet werden.</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">h) Automatisierte Entscheidungen im Einzelfall einschließlich Profiling</h2>
              <p className="my-4">Jede von der Verarbeitung personenbezogener Daten betroffene Person hat das vom Europäischen Richtlinien- und Verordnungsgeber gewährte Recht, nicht einer ausschließlich auf einer automatisierten Verarbeitung — einschließlich Profiling — beruhenden Entscheidung unterworfen zu werden, die ihr gegenüber rechtliche Wirkung entfaltet oder sie in ähnlicher Weise erheblich beeinträchtigt, sofern die Entscheidung (1) nicht für den Abschluss oder die Erfüllung eines Vertrags zwischen der betroffenen Person und dem Verantwortlichen erforderlich ist, oder (2) aufgrund von Rechtsvorschriften der Union oder der Mitgliedstaaten, denen der Verantwortliche unterliegt, zulässig ist und diese Rechtsvorschriften angemessene Maßnahmen zur Wahrung der Rechte und Freiheiten sowie der berechtigten Interessen der betroffenen Person enthalten oder (3) mit ausdrücklicher Einwilligung der betroffenen Person erfolgt.</p>
              <p className="my-4">Ist die Entscheidung (1) für den Abschluss oder die Erfüllung eines Vertrags zwischen der betroffenen Person und dem Verantwortlichen erforderlich oder (2) erfolgt sie mit ausdrücklicher Einwilligung der betroffenen Person, trifft die AirClean VS angemessene Maßnahmen, um die Rechte und Freiheiten sowie die berechtigten Interessen der betroffenen Person zu wahren, wozu mindestens das Recht auf Erwirkung des Eingreifens einer Person seitens des Verantwortlichen, auf Darlegung des eigenen Standpunkts und auf Anfechtung der Entscheidung gehört.</p>
              <p className="my-4">Möchte die betroffene Person Rechte mit Bezug auf automatisierte Entscheidungen geltend machen, kann sie sich hierzu jederzeit an einen Mitarbeiter des für die Verarbeitung Verantwortlichen wenden</p>

              <h2 className="text-2xl font-bold text-slate-800 mt-10 mb-4">i) Recht auf Widerruf einer datenschutzrechtlichen Einwilligung</h2>
              <p className="my-4">Jede von der Verarbeitung personenbezogener Daten betroffene Person hat das vom Europäischen Richtlinien- und Verordnungsgeber gewährte Recht, eine Einwilligung zur Verarbeitung personenbezogener Daten jederzeit zu widerrufen.</p>
              <p className="my-4">Möchte die betroffene Person ihr Recht auf Widerruf einer Einwilligung geltend machen, kann sie sich hierzu jederzeit an einen Mitarbeiter des für die Verarbeitung Verantwortlichen wenden.</p>

              <h1 className="text-3xl font-bold text-slate-800 mt-10 mb-4">10. Rechtsgrundlage der Verarbeitung</h1>
              <p className="my-4">Art. 6 I lit. a DSGVO dient unserem Unternehmen als Rechtsgrundlage für Verarbeitungsvorgänge, bei denen wir eine Einwilligung für einen bestimmten Verarbeitungszweck einholen. Ist die Verarbeitung personenbezogener Daten zur Erfüllung eines Vertrags, dessen Vertragspartei die betroffene Person ist, erforderlich, wie dies beispielsweise bei Verarbeitungsvorgängen der Fall ist, die für eine Lieferung von Waren oder die Erbringung einer sonstigen Leistung oder Gegenleistung notwendig sind, so beruht die Verarbeitung auf Art. 6 I lit. b DSGVO. Gleiches gilt für solche Verarbeitungsvorgänge, die zur Durchführung vorvertraglicher Maßnahmen erforderlich sind, etwa in Fällen von Anfragen zu unseren Produkten oder Leistungen. Unterliegt unser Unternehmen einer rechtlichen Verpflichtung, durch welche eine Verarbeitung von personenbezogenen Daten erforderlich wird, wie beispielsweise zur Erfüllung steuerlicher Pflichten, so basiert die Verarbeitung auf Art. 6 I lit. c DSGVO. In seltenen Fällen könnte die Verarbeitung von personenbezogenen Daten erforderlich werden, um lebenswichtige Interessen der betroffenen Person oder einer anderen natürlichen Person zu schützen. Dies wäre beispielsweise der Fall, wenn ein Besucher in unserem Betrieb verletzt werden würde und daraufhin sein Name, sein Alter, seine Krankenkassendaten oder sonstige lebenswichtige Informationen an einen Arzt, ein Krankenhaus oder sonstige Dritte weitergegeben werden müssten. Dann würde die Verarbeitung auf Art. 6 I lit. d DSGVO beruhen. Letztlich könnten Verarbeitungsvorgänge auf Art. 6 I lit. f DSGVO beruhen. Auf dieser Rechtsgrundlage basieren Verarbeitungsvorgänge, die von keiner der vorgenannten Rechtsgrundlagen erfasst werden, wenn die Verarbeitung zur Wahrung eines berechtigten Interesses unseres Unternehmens oder eines Dritten erforderlich ist, sofern die Interessen, Grundrechte und Grundfreiheiten des Betroffenen nicht überwiegen. Solche Verarbeitungsvorgänge sind uns insbesondere deshalb gestattet, weil sie durch den europäischen Gesetzgeber besonders erwähnt wurden. Er vertrat insoweit die Auffassung, dass ein berechtigtes Interesse anzunehmen sein könnte, wenn die betroffene Person ein Kunde des Verantwortlichen ist (Erwägungsgrund 47 Satz 2 DSGVO).</p>

              <h1 className="text-3xl font-bold text-slate-800 mt-10 mb-4">11. Berechtigte Interessen an der Verarbeitung, die von dem Verantwortlichen oder einem Dritten verfolgt werden</h1>
              <p className="my-4">Basiert die Verarbeitung personenbezogener Daten auf Artikel 6 I lit. f DSGVO ist unser berechtigtes Interesse die Durchführung unserer Geschäftstätigkeit.</p>

              <h1 className="text-3xl font-bold text-slate-800 mt-10 mb-4">12. Dauer, für die die personenbezogenen Daten gespeichert werden</h1>
              <p className="my-4">Das Kriterium für die Dauer der Speicherung von personenbezogenen Daten ist die jeweilige gesetzliche Aufbewahrungsfrist. Nach Ablauf der Frist werden die entsprechenden Daten routinemäßig gelöscht, sofern sie nicht mehr zur Vertragserfüllung oder Vertragsanbahnung erforderlich sind.</p>

              <h1 className="text-3xl font-bold text-slate-800 mt-10 mb-4">13. Gesetzliche oder vertragliche Vorschriften zur Bereitstellung der personenbezogenen Daten; Erforderlichkeit für den Vertragsabschluss; Verpflichtung der betroffenen Person, die personenbezogenen Daten bereitzustellen; mögliche Folgen der Nichtbereitstellung</h1>
              <p className="my-4">Wir klären Sie darüber auf, dass die Bereitstellung personenbezogener Daten zum Teil gesetzlich vorgeschrieben ist (z.&nbsp;B. Steuervorschriften) oder sich auch aus vertraglichen Regelungen (z.&nbsp;B. Angaben zum Vertragspartner) ergeben kann. Mitunter kann es zu einem Vertragsschluss erforderlich sein, dass eine betroffene Person uns personenbezogene Daten zur Verfügung stellt, die in der Folge durch uns verarbeitet werden müssen. Die betroffene Person ist beispielsweise verpflichtet, uns personenbezogene Daten bereitzustellen, wenn unser Unternehmen mit ihr einen Vertrag abschließt. Eine Nichtbereitstellung der personenbezogenen Daten hätte zur Folge, dass der Vertrag mit dem Betroffenen nicht geschlossen werden könnte. Vor einer Bereitstellung personenbezogener Daten durch den Betroffenen muss sich der Betroffene an einen unserer Mitarbeiter wenden. Unser Mitarbeiter klärt den Betroffenen einzelfallbezogen darüber auf, ob die Bereitstellung der personenbezogenen Daten gesetzlich oder vertraglich vorgeschrieben oder für den Vertragsabschluss erforderlich ist, ob eine Verpflichtung besteht, die personenbezogenen Daten bereitzustellen, und welche Folgen die Nichtbereitstellung der personenbezogenen Daten hätte.</p>

              <h1 className="text-3xl font-bold text-slate-800 mt-10 mb-4">14. Bestehen einer automatisierten Entscheidungsfindung</h1>
              <p className="my-4">Als verantwortungsbewusstes Unternehmen verzichten wir auf eine automatische Entscheidungsfindung oder ein Profiling.</p>

              <h1 className="text-3xl font-bold text-slate-800 mt-10 mb-4">15. Datenschutzbeauftragter</h1>
              <p className="my-4">
                Wenn Sie unsere Datenschutzbeauftragte erreichen wollen, schreiben Sie eine Mail an&nbsp;
                <a href="mailto:datenschutz@sb-clean.de"></a>
                <a href="mailto:datenschutz@sb-clean.de">datenschutz@sb-clean.de</a>
              </p>
              <p className="my-4">Wir bitten Sie, sich regelmäßig über den Inhalt unserer Datenschutzerklärung zu informieren. Wir passen die Datenschutzerklärung an, sobald die Änderungen der von uns durchgeführten Datenverarbeitungen dies erforderlich machen. Wir informieren Sie, sobald durch die Änderungen eine Mitwirkungshandlung Ihrerseits (z.&nbsp;B. Einwilligung) oder eine sonstige individuelle Benachrichtigung erforderlich wird.</p>
              <p className="my-4">Diese Datenschutzerklärung ist aktuell gültig und hat den Stand Januar 2022. Durch die Weiterentwicklung unserer Website und Angebote darüber oder aufgrund geänderter gesetzlicher beziehungsweise behördlicher Vorgaben kann es notwendig werden, diese Datenschutzerklärung zu ändern. Die jeweils aktuelle Datenschutzerklärung kann jederzeit auf unserer Website unter dem Menüpunkt „Datenschutz“ von Ihnen abgerufen und ausgedruckt werden.</p>

            </div>
          </div>

        </div>
      </MainLayout>
    </>
  )
}